# Generated by Django 4.2 on 2025-03-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_education", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="lessons/"),
        ),
    ]
